// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNDYayqt99-LI4-_sIO0sl5avTNm4HGhc',
    appId: '1:717012696191:web:2261dc97f39236253e534a',
    messagingSenderId: '717012696191',
    projectId: 'dormsityapp',
    authDomain: 'dormsityapp.firebaseapp.com',
    storageBucket: 'dormsityapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoLj-IZbXsVQ3Q3Azzg6XLtzZuUM_uSsU',
    appId: '1:717012696191:android:ae7356457225bfc33e534a',
    messagingSenderId: '717012696191',
    projectId: 'dormsityapp',
    storageBucket: 'dormsityapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApq49c3m_CFEyaPtMSU5KghLWFfagQgso',
    appId: '1:717012696191:ios:7f8f161e4573f9b43e534a',
    messagingSenderId: '717012696191',
    projectId: 'dormsityapp',
    storageBucket: 'dormsityapp.appspot.com',
    iosBundleId: 'com.example.dormsityAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApq49c3m_CFEyaPtMSU5KghLWFfagQgso',
    appId: '1:717012696191:ios:7f8f161e4573f9b43e534a',
    messagingSenderId: '717012696191',
    projectId: 'dormsityapp',
    storageBucket: 'dormsityapp.appspot.com',
    iosBundleId: 'com.example.dormsityAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNDYayqt99-LI4-_sIO0sl5avTNm4HGhc',
    appId: '1:717012696191:web:02f786f54fe7899e3e534a',
    messagingSenderId: '717012696191',
    projectId: 'dormsityapp',
    authDomain: 'dormsityapp.firebaseapp.com',
    storageBucket: 'dormsityapp.appspot.com',
  );

}